# Generated by Django 5.2.7 on 2025-10-05 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=200, verbose_name='Origem')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('data_saida', models.DateTimeField(verbose_name='Data/Hora de Saída')),
                ('data_chegada', models.DateTimeField(verbose_name='Data/Hora de Chegada')),
                ('quilometragem', models.PositiveIntegerField(verbose_name='Quilometragem (km)')),
                ('descricao', models.TextField(verbose_name='Descrição/Objetivo do Trajeto')),
            ],
            options={
                'verbose_name': 'Trajeto',
                'verbose_name_plural': 'Trajetos',
                'ordering': ['data_saida'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Data/Hora de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data/Hora de Fim')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20, verbose_name='Status')),
                ('motivo_reprovacao', models.TextField(blank=True, verbose_name='Motivo da Reprovação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
