# Generated by Django 5.2.7 on 2025-10-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pergunta_seguranca_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pergunta de Segurança 1'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pergunta_seguranca_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pergunta de Segurança 2'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='resposta_seguranca_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Resposta de Segurança 1'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='resposta_seguranca_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Resposta de Segurança 2'),
        ),
    ]
