# Generated by Django 5.2.7 on 2025-10-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_pergunta_seguranca_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este e-mail já está cadastrado.'}, max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
