# Generated by Django 5.2.7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_make_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_ativacao',
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name='Token de Ativação'
            ),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_criado_em',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Token Criado Em'
            ),
        ),
    ]
