# Generated by Django 5.2.7 on 2026-05-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('usuarios', '0006_criar_grupos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='campus.campus', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_habilitacao',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número da CNH'),
        ),
    ]
