# Generated by Django 5.2.7 on 2026-05-25 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome do Campus')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
                'ordering': ['nome'],
            },
        ),
    ]
