# Generated by Django 5.2.7 on 2026-05-25 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0002_initial'),
        ('veiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_posto', models.CharField(max_length=200, verbose_name='Local / Nome do Posto')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('km_atual', models.PositiveIntegerField(verbose_name='Km Atual do Veículo')),
                ('litros_abastecidos', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Litros Abastecidos')),
                ('valor_gasto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Gasto (R$)')),
                ('tipo_combustivel', models.CharField(choices=[('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('diesel', 'Diesel'), ('gnv', 'GNV'), ('eletrico', 'Elétrico')], default='gasolina', max_length=20, verbose_name='Tipo de Combustível')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='agendamentos.agendamento', verbose_name='Agendamento Relacionado')),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to=settings.AUTH_USER_MODEL, verbose_name='Motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('acidente', 'Acidente'), ('pane', 'Pane Mecânica'), ('multa', 'Multa de Trânsito'), ('furto', 'Furto / Roubo'), ('avaria', 'Avaria / Dano'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Ocorrência')),
                ('gravidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Gravidade')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora da Ocorrência')),
                ('local', models.CharField(max_length=200, verbose_name='Local da Ocorrência')),
                ('descricao', models.TextField(verbose_name='Descrição da Ocorrência')),
                ('providencias_tomadas', models.TextField(blank=True, verbose_name='Providências Tomadas')),
                ('numero_boletim', models.CharField(blank=True, max_length=50, verbose_name='Nº Boletim de Ocorrência (BO)')),
                ('resolvido', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='agendamentos.agendamento', verbose_name='Agendamento')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to=settings.AUTH_USER_MODEL, verbose_name='Motorista / Responsável')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data_hora'],
            },
        ),
    ]
