# Generated by Django 5.2.7 on 2026-06-08 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_initial'),
        ('frotas', '0001_initial'),
        ('veiculos', '0002_veiculo_campus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deslocamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origem', models.CharField(blank=True, max_length=200, verbose_name='Origem')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('data_hora_saida', models.DateTimeField(verbose_name='Data/Hora de Saída')),
                ('data_hora_chegada', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Chegada')),
                ('km_saida', models.PositiveIntegerField(verbose_name='Km na Saída')),
                ('km_chegada', models.PositiveIntegerField(blank=True, null=True, verbose_name='Km na Chegada')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deslocamentos', to='agendamentos.agendamento', verbose_name='Agendamento Relacionado')),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deslocamentos', to=settings.AUTH_USER_MODEL, verbose_name='Motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deslocamentos', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Deslocamento',
                'verbose_name_plural': 'Deslocamentos',
                'ordering': ['-data_hora_saida'],
            },
        ),
    ]
