# Generated by Django 5.2.7 on 2026-06-08 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_trajeto_motorista'),
        ('frotas', '0002_deslocamento'),
        ('veiculos', '0002_veiculo_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='deslocamento',
            name='trajeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deslocamentos', to='agendamentos.trajeto', verbose_name='Trajeto Atribuído'),
        ),
        migrations.AlterField(
            model_name='deslocamento',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deslocamentos', to='veiculos.veiculo', verbose_name='Veículo'),
        ),
    ]
