# Generated by Django 5.2.7 on 2026-06-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_trajeto_motorista'),
        ('frotas', '0003_deslocamento_trajeto_alter_deslocamento_veiculo'),
        ('veiculos', '0002_veiculo_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='trajeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='agendamentos.trajeto', verbose_name='Trajeto Atribuído'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='trajeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='agendamentos.trajeto', verbose_name='Trajeto Atribuído'),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='veiculos.veiculo', verbose_name='Veículo'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='agendamentos.agendamento', verbose_name='Agendamento'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='veiculos.veiculo', verbose_name='Veículo'),
        ),
    ]
